export const cashew = {
  anthracnose: [
    "https://www.youtube.com/watch?v=If-YQLJYmdg",
    "https://youtu.be/F5uq70ITY-Q?si=-m8REDRwXWuI5T_B",
    "https://www.youtube.com/watch?v=zTZ_oya3HP4",
    "https://www.youtube.com/watch?v=D4geWo_4Xls",
  ],
  gumosis: [
    "https://www.youtube.com/watch?v=If-YQLJYmdg",
    "https://www.youtube.com/watch?v=D4geWo_4Xls",
    "https://youtu.be/MfACkBjQyV0?si=NjZa2vGl1brklsPH",
    "https://www.youtube.com/watch?v=D4geWo_4Xls",
  ],
  healthy: [
    "https://www.youtube.com/watch?v=D4geWo_4Xls",
    "http://www.youtube.com/watch?v=zbhuVcbTHsU",
    "http://www.youtube.com/watch?v=D4geWo_4Xls",
    "http://www.youtube.com/watch?v=e6mdroPV0yg",
    "https://www.youtube.com/watch?v=If-YQLJYmdg",
  ],
  leaf_miner: [
    "https://www.youtube.com/watch?v=D4geWo_4Xls",
    "https://youtu.be/XnRl37DLrHs?si=El09XR9Rd1cH2aOf",
    "https://www.youtube.com/watch?v=C8JjPLoY-ps",
    "https://www.youtube.com/watch?v=bTHHdalc7hQ&pp=0gcJCfwAo7VqN5tD",
    "https://www.youtube.com/watch?v=eMFGZTJ6sKM&pp=ygUMI2xlYWZ5dHJhaWxz",
    "https://www.youtube.com/watch?v=If-YQLJYmdg",
  ],

  red_rust: [
    "https://www.youtube.com/watch?v=D4geWo_4Xls",
    "https://www.youtube.com/watch?v=czB4Za0mby8&pp=0gcJCfwAo7VqN5tD",
    "https://www.youtube.com/shorts/9MBlhV7i0Sk",
    "https://www.youtube.com/watch?v=Z0qpWlYJwPs&pp=ugMICgJrbxABGAE%3D",
    "https://www.youtube.com/watch?v=If-YQLJYmdg",
  ],
};

export const cassava = {
  bacterial_blight: [
    "https://www.youtube.com/watch?v=l4YFBS_LPIg",
    "https://www.youtube.com/watch?v=pGhSnvgolyw",
    "https://www.youtube.com/watch?v=nbEzNvNyx9k",
  ],
  brown_spot: [
    "https://www.youtube.com/watch?v=F_LEL7G2SjA",
    "https://www.youtube.com/watch?v=O__LVsNZmRw",
    "http://www.youtube.com/watch?v=A0gNsOZePI4",
  ],
  green_mite: ["https://youtu.be/KpT9ZDPezWo?si=QxC6oNXjgUUsR-uP"],
  healthy: ["https://youtu.be/KpT9ZDPezWo?si=QxC6oNXjgUUsR-uP"],
  mosaic: [
    "https://www.youtube.com/watch?v=8kqNiqTrZA8",
    "https://www.youtube.com/watch?v=oNvwMOk02AY",
    "https://www.youtube.com/watch?v=I1lHM7rbd9g",
    "https://youtu.be/KpT9ZDPezWo?si=QxC6oNXjgUUsR-uP",
    "https://www.youtube.com/watch?v=Rh65AFtwmXc",
    "https://www.youtube.com/watch?v=nbEzNvNyx9k",
    "https://www.youtube.com/watch?v=YyUKdwkYW6U",
    "https://youtu.be/8GYEOdBhZL8?si=PLhZvxZvIIzvCZWC",
    "https://www.youtube.com/watch?v=Mj8NOA7CNCQ",
  ],
};

export const maize = {
  fall_armyworm: [
    "https://www.youtube.com/watch?v=dMAjrniW1yY",
    "https://www.youtube.com/watch?v=RXAtur2c3QM",
    "https://www.youtube.com/watch?v=vddhs7PjXhM",
    "https://www.youtube.com/watch?v=bAAQDaDl-FY",
    "https://www.youtube.com/watch?v=E_jTyGG9cF4",
    "https://www.youtube.com/watch?v=GR6A7_-rFb4",
    "https://www.youtube.com/watch?v=J6Id9IRfzoA",
    "https://www.youtube.com/watch?v=fRyiz-fah34",
    "https://www.youtube.com/watch?v=3sTTCzev97I",
    "https://www.youtube.com/watch?v=msemvWxmRP4",
    "https://www.youtube.com/watch?v=P-Jx7Ru2wDw",
    "https://www.youtube.com/watch?v=QxbUzlxlB-M",
    "https://www.tiktok.com/@mudhumeni_mukuru/video/7419432635908345094",
  ],
  grasshopper: [
    "https://www.youtube.com/watch?v=__VQHJ4gqig",
    "https://www.youtube.com/watch?v=gLIhLvcuRjM",
    "https://www.youtube.com/watch?v=lXgXQwebSzs",
    "https://www.youtube.com/watch?v=QcUHu8vmvhw",
  ],
  healthy: [
    "https://www.youtube.com/watch?v=LgEyPG0msMM",
    "https://www.youtube.com/watch?v=ns1za21DLkk",
    "https://www.youtube.com/watch?v=xNqv4qRYcyo",
    "https://www.youtube.com/watch?v=__VQHJ4gqig",
  ],
  leaf_beetle: [
    "https://www.youtube.com/watch?v=-qUTvO6kP0c",
    "https://www.youtube.com/watch?v=HvlmO1DzbkA",
    "https://www.youtube.com/watch?v=5jQSKDWU9Zs",
    "https://www.youtube.com/watch?v=epvObbNjq5M",
    "https://www.youtube.com/watch?v=__VQHJ4gqig",
  ],
  leaf_blight: [
    "https://www.youtube.com/watch?v=uafRy5EqwBQ",
    "https://www.youtube.com/watch?v=eil5txCZgSQ",
    "https://www.youtube.com/watch?v=yxe0kiuJLRI",
    "https://www.youtube.com/watch?v=gLIhLvcuRjM",
    "https://www.youtube.com/watch?v=__VQHJ4gqig",
    "https://www.youtube.com/watch?v=OmoAjymdVi4",
  ],
  leaf_spot: [
    "https://www.youtube.com/watch?v=OmoAjymdVi4",
    "https://www.youtube.com/watch?v=HvlmO1DzbkA",
    "https://www.youtube.com/watch?v=__VQHJ4gqig",
    "https://www.youtube.com/watch?v=DJfBYtyr0Dg",
  ],
  streak_virus: [
    "https://www.youtube.com/watch?v=l3IcSDdYDFA",
    "https://www.youtube.com/watch?v=6ae1HkqzXLs",
    "https://www.youtube.com/watch?v=TAM9cdEEO4A",
    "https://www.youtube.com/watch?v=DDrrYdzYPpY",
    "https://www.youtube.com/watch?v=P2RmSiwp_1U",
    "https://www.youtube.com/watch?v=5eEjDsLu1DQ",
    "https://www.youtube.com/watch?v=__VQHJ4gqig",
  ],
};

export const tomato = {
  healthy: [
    "https://www.youtube.com/watch?v=3u_7NTMB6z8",
    "https://www.youtube.com/watch?v=igZkduQQeDU",
    "https://www.youtube.com/watch?v=jIYVvGTLpqc&pp=0gcJCfwAo7VqN5tD",
    "https://www.youtube.com/watch?v=wd-TUweqY6c",
    "https://www.youtube.com/watch?v=BJLQjHJVTwg&pp=ygUZI2VuZ2lzYWZlX3RvX21pbmltYWxfZmFybQ%3D%3D",
  ],
  leaf_blight: [
    "https://www.youtube.com/watch?v=QEuknYpO7Eo",
    "https://www.youtube.com/watch?v=dKAjQ-Gy-aM&pp=ygULI2Vhcmx5YmxpdGU%3D",
    "https://www.youtube.com/watch?v=Lf6LrtuqFm8",
    "https://www.youtube.com/watch?v=08XXSaWd3aw&pp=0gcJCdgAo7VqN5tD",
    "https://www.youtube.com/watch?v=V0TMPp7BDAM",
    "https://www.youtube.com/watch?v=45UFdS2FkFM",
    "https://www.youtube.com/watch?v=rG7YdE3JJwg",
  ],
  leaf_curl: [
    "https://www.youtube.com/watch?v=GRkC8oHUMYA&pp=0gcJCfwAo7VqN5tD",
    "https://www.youtube.com/watch?v=lqAaRrvDPAo",
    "https://www.youtube.com/watch?v=-lLZMCv9j50",
    "https://www.youtube.com/watch?v=D-58aAFIyCQ&pp=ygULI2N1cmxfdmlydXM%3D",
    "https://www.youtube.com/watch?v=JneZ5woeCpE&pp=0gcJCfwAo7VqN5tD",
    "https://www.youtube.com/watch?v=gsaWvzghaYQ",
    "https://www.youtube.com/watch?v=FV3uzTX79pw",
    "https://www.youtube.com/watch?v=_Yv0NOvdpJg&vl=ja",
    "https://www.youtube.com/watch?v=kECabqMxQ-c&pp=ygULI2Zha2hhcmF5YXQ%3D",
  ],
  septoria_leaf_spot: [
    "https://www.youtube.com/watch?v=puyD8VPrV94",
    "https://www.youtube.com/watch?v=bI0B4IsQT3w",
    "https://www.youtube.com/watch?v=EueZRKL7uMA",
    "https://www.youtube.com/watch?v=n0CSsdLQ8BQ",
    "https://www.youtube.com/watch?v=dKAjQ-Gy-aM&pp=ygULI2Vhcmx5YmxpdGU%3D",
    "https://www.youtube.com/watch?v=bDQ0ZEYNTNc",
    "https://www.youtube.com/watch?v=iHN5DMCRkrU",
    "https://www.youtube.com/watch?v=kECabqMxQ-c&pp=ygULI2Zha2hhcmF5YXQ%3D",
  ],
  verticullium_wilt: [
    "https://www.youtube.com/watch?v=HymmOGQBTCM",
    "https://www.youtube.com/watch?v=iizHOwWWSyM",
    "https://m.youtube.com/watch?v=3uBmI2Wowvo",
    "https://www.youtube.com/watch?v=-HPZgtynNZo",
    "https://www.youtube.com/watch?v=Dc-1UW0IEuU",
    "https://www.youtube.com/watch?v=ef8j5yzxhH0",
    "https://www.youtube.com/watch?v=CqBSVaB9p6w",
  ],
};
